defaults:
  - runner: batched_offline
  - algo: dqn
  - model: q_network
training:
  seed: 1
runner:
  n_steps: 1e6
  kwargs:
    log_interval_episodes: 10
    log_dir_path: './'
    store_checkpoint: True
    checkpoint_type: 'interval'
    checkpoint_freq: 5000
    checkpoint_dir_path: './checkpoints/'
    load_model_path: null
env:
  kwargs:
    env_name: 'breakout'
algo:
  cls_string: 'DQN'
  kwargs:
    discount_gamma: 0.99
model:
  cls_string: 'QNetwork'
  kwargs: {}
